config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about', to: "homes#about"
  devise_for :users
  resources :users
  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :check_book_user, only: [:edit, :update, :destroy]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)

    #何故、↓を入れないと投稿の際、user must exit errorが起きるのか？
    #アソシエーションにより、bookには誰が投稿したかという情報を持たせる必要がある

    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully"
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit

    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully"
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def check_book_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def index
    @user = current_user
    @new_book = Book.new
    @users = User.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully"
    else
      @user = current_user
      @books = Book.all
      redirect_to books_path
    end
  end

  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @books = Book.where(user_id:@user.id)
    
    #@bookを@new_bookにしたら投稿できるようになったのは何故ですか？
    #ここに定義されてないものをform_withで使おうとすると自動的にコントローラーに対応するものを作ろうとする
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully"
    else
      #redirect_to edit_user_path(@user)
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def check_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new_book.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: new_book, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Opinion</label><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render "layouts/error_messages", error: @book %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Opinion</label><br>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book %>
    <%= render "layouts/error_messages", error: @book %>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/user_info", user: @user %>
      <%= render "books/new_book", new_book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/user_info", user: @user %>
      <%= render "books/new_book", new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user_id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book) %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @book.user_id == current_user.id %>
                <td>
                  <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
                </td>
                <td>
                  <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm"=>"本当に消しますか？" %>
                </td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
      </h1>
      <p>
        In <i class="fas fa-book"></i><strong>Bookers</strong>,
      </p>
      <p>
        you can share and exchange your opinions , inpressions , and emotions
      </p>
      <p>
        about various books!
      </p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block btn-sm mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-block btn-sm"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if error.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(error.errors.count, "errors") %>prohibited this user from being saved: 
    </h2>
    <ul>
      <% error.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/601fba1a81.js" crossorigin="anonymous"></script>

    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a href="/" class="navbar-brand">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!--ログインしているかどうか-->
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: "fas fa-home nav-link text-light" do %>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "fas fa-users nav-link text-light" do %>
                    Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "fas fa-book-open nav-link text-light" do %>
                    Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" do %>
                    logout
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "fas fa-home nav-link text-light" do %>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path, class: "fas fa-link nav-link text-light" do %>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "fas fa-user-plus nav-link text-light" do %>
                    sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" do %>
                    login
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>  
      </nav>
    </header>
    
    <main>
      <p id="notice">
        <%= notice %>
      </p>
      <%= yield %>
    </main>
   
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user), class: "btn btn-block btn-outline-secondary btn-sm mt-4" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <!--<% if user.id == current_user.id %>-->
  <!--  <%= link_to edit_user_path(user), class: "btn btn-block btn-outline-secondary btn-sm mt-4" do %>-->
  <!--    <i class="fas fa-user-cog"></i>-->
  <!--  <% end %>-->
  <!--<% else %>-->
  <!--  <%= link_to user_path(current_user), class: "btn btn-block btn-outline-secondary btn-sm mt-4" do %>-->
  <!--    <i class="fas fa-user-cog"></i>-->
  <!--  <% end %>-->
  <!--<% end %>-->
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render "layouts/error_messages", error: @user %>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form_group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form_group">
          <label>Image</label><br>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form_group">
          <%= f.label :introduction %><br>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form_group">
          <%= f.submit "Update User", class: "btn btn-secondary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/user_info", user: @user %>
      <%= render "books/new_book", new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/user_info", user: @user %>

      <%# @bookを@new_bookにしたら投稿できるようになったのは何故ですか？
      ターミナルを確認してみた所、投稿する場合 post /book
      しかし、投稿出来ない時はpost book/id になっていた%>

      <%= render "books/new_book", new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image,:fill, 50, 50, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>